apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: chensiyingcrystal/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: chensiyingcrystal/client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: chensiyingcrystal/tickets
    context: tickets
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: chensiyingcrystal/orders
    context: orders
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: chensiyingcrystal/expiration
    context: expiration
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: chensiyingcrystal/payments
    context: payments
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile

